package com.morningglory.basic.webservice.at.com.ctc.ema.server.jwsserver.sms;

import com.morningglory.basic.webservice.at.net.java.dev.jaxb.array.StringArray;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2019-04-22T15:00:42.780+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", name = "ISmsOperator")
//@XmlSeeAlso({net.java.dev.jaxb.array.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ISmsOperator {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", partName = "return")
    public MtMessageRes sendSms(
        @WebParam(partName = "arg0", name = "arg0")
        String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        String arg2,
        @WebParam(partName = "arg3", name = "arg3")
                MtMessage arg3
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", partName = "return")
    public BalanceRes getBalance(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", partName = "return")
    public MtMessageRes bathSendSms(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
                MtMessageArray arg3
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", partName = "return")
    public ReportMessageRes getReport(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", partName = "return")
    public MtMessageRes massBathSendSms(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        java.lang.String arg4,
        @WebParam(partName = "arg5", name = "arg5")
                StringArray arg5,
        @WebParam(partName = "arg6", name = "arg6")
        java.lang.String arg6
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", partName = "return")
    public MoMessageRes getSms(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );
}
