
package com.morningglory.basic.webservice.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmsOperatorImpService", targetNamespace = "http://sms.jwsserver.server.ema.ctc.com/", wsdlLocation = "http://192.168.12.69:8080/smg/webService/smsOper?wsdl")
public class SmsOperatorImpService
    extends Service
{

    private final static URL SMSOPERATORIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSOPERATORIMPSERVICE_EXCEPTION;
    private final static QName SMSOPERATORIMPSERVICE_QNAME = new QName("http://sms.jwsserver.server.ema.ctc.com/", "SmsOperatorImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.12.69:8080/smg/webService/smsOper?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSOPERATORIMPSERVICE_WSDL_LOCATION = url;
        SMSOPERATORIMPSERVICE_EXCEPTION = e;
    }

    public SmsOperatorImpService() {
        super(__getWsdlLocation(), SMSOPERATORIMPSERVICE_QNAME);
    }

    public SmsOperatorImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSOPERATORIMPSERVICE_QNAME, features);
    }

    public SmsOperatorImpService(URL wsdlLocation) {
        super(wsdlLocation, SMSOPERATORIMPSERVICE_QNAME);
    }

    public SmsOperatorImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSOPERATORIMPSERVICE_QNAME, features);
    }

    public SmsOperatorImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsOperatorImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISmsOperator
     */
    @WebEndpoint(name = "SmsOperatorImpPort")
    public ISmsOperator getSmsOperatorImpPort() {
        return super.getPort(new QName("http://sms.jwsserver.server.ema.ctc.com/", "SmsOperatorImpPort"), ISmsOperator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISmsOperator
     */
    @WebEndpoint(name = "SmsOperatorImpPort")
    public ISmsOperator getSmsOperatorImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sms.jwsserver.server.ema.ctc.com/", "SmsOperatorImpPort"), ISmsOperator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSOPERATORIMPSERVICE_EXCEPTION!= null) {
            throw SMSOPERATORIMPSERVICE_EXCEPTION;
        }
        return SMSOPERATORIMPSERVICE_WSDL_LOCATION;
    }

}
