spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 7081