spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
mybatis:
  type-aliases-package: com.morningglory.model
  mapper-locations: classpath:mapper/*.xml

server:
  port: 7081

logging:
  level:
    com:
      morningglory:
        mvc:
          dao: debug
    root: INFO

es:
  host: 127.0.0.1
  port: 9200

canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  subscribe: demo\\..*

