spring:
  output:
    ansi:
      enabled: always
  profiles:
#    include: common
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=false
    ##url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
mybatis:
  type-aliases-package: com.morningglory.model
  mapper-locations: classpath:mapper/*.xml

server:
  port: 7081

logging:
  level:
    com.morningglory.mvc: info
    com:
      morningglory:
        mvc:
          dao: debug
    root: INFO
  pattern:
    #console: "%yellow%d{yyyy-MM-dd-HH:mm:ss} %-5level [%X{requestId}] [%thread]  %logger- %msg%n"
    #console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%green(%-5level)] [%magenta(%X{requestId})] --- [%15thread] %cyan(%-45.45logger{45}) :%msg%n"


es:
  host: 127.0.0.1
  port: 9200

canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  subscribe: demo\..*,cnooc_acl\..*,cnooc_item\..*,mytest\..*



terminus:
  acl:
    projectCode: cnooc
    defaultTenant: 10000000000
    dubbo:
      registers:
      - zookeeper://127.0.0.1:2181
    dataAuth:
      mybatisProxy: false
      terminusEsProxy: false
      extensionProxy: true
      basePackages: com.morningglory.mvc.controller
      methods:
       -
        name: list
        params: java.lang.Long
       -
        name: list1
        params:


mg:
  properties:
    enable: true
  properties1:
    items:
      -
        name: name1
        path: path1
      -
        name: name2
        path: path2

  properties2:
    items:
      index1:
        name: name1
        path: path1
      index2:
        name: name2
        path: path2



