spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?characterEncoding=utf8&useSSL=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.morningglory.model
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080

logging:
  level:
    com:
      morningglory:
        mvc:
          dao: debug
    root: INFO